### PR TITLE
Hotfix - Scroll fabrary matchups

### PR DESCRIPTION
**Pull request by brianmclachlin**
Scrolls the fabrary matchups list if the list exceeds the given space.

### CODE REVIEW

**Comment by LaustinSpayce** [comment]
closes #153

**Comment by brianmclachlin** [comment]
Only does the scrollbar at the moment, so doesn't completely close #153. You could merge it in if you want and the `usort` could come afterwards.

**Comment by LaustinSpayce** [comment]
Yeah ok I'll update the comment and as it's only like 2 lines I'll approve n merge it now. OotTheMonk can push to the server later.

**Review by LaustinSpayce — APPROVED** [review]

**Comment by LaustinSpayce** [comment]
image
I also checked it on my local dev we good

**Pull request merged**
