### PR TITLE
Sigils

### PR DESCRIPTION
**Pull request by Pgibby8**
adding the missing sigils (lightning, earth, and brilliance)

### CODE REVIEW

**Comment by CarlosRoig** [comment]
Please remove the cards implemented from the folder "New Cards"

**Comment by Pgibby8** [comment]
> p

As in remove the .webp files? I'm new to contributing, so could you explain what those files do?

**Comment by CarlosRoig** [comment]
Yes, the .webb files in the folder "New Cards".
When you implement a card, it is best practice to remove the image from that folder, so that we can see which cards are left to implement :)

**Comment by Pgibby8** [comment]
whoops, accidentally capitalized Sigils in my last push. I'll switch over to that pull request.

**Pull request closed without merging**
