### PR TITLE
#510 Briar hero ability on hit

### PR DESCRIPTION
**Pull request by lukeputz92**

### CODE REVIEW

**Comment by OotTheMonk** [comment]
I don't think using NumAttacks would work. Consider this scenario:
Briar attacks with a go again attack. It does not deal damage. Now attack with a different attack, and it does deal damage. This should create an earth token, but I believe it will not because num attacks is 2 now.

**Review by OotTheMonk — CHANGES_REQUESTED** [review]
See comment in conversation

**Comment by lukeputz92** [comment]
what about this? As far as I can tell, $numHitsOnLink += intval($combatChainState[$CCS_HitThisLink]) on line 986 of NetworkLibraries may have been backwards because we would want to increment combatChainState[$CCS_HitThisLink] when damage is resolved right? I tested with Briar and few other heroes and it seems to be working. Let me know if not. Thanks!

**Comment by OotTheMonk** [comment]
This part is not correct I believe because it's possible to have multiple hits on one link; for example if flick knives is activated:
image

This part I am not sure about since I don't know where else this is set, but I worry that setting instead of incrementing would overwrite things like flick knives mentioned above:
image

This part I have a few comments; one is you don't need to check if the attack hit here, since this is in the hit effect function. It only gets called when the attack hits. You wouldn't want to use hits on link for briar, as she only cares about if the attack itself counts as dealing damage. The other thing I think that is missing from this code snippet is how we are preventing briar from creating multiple earth tokens in one turn - Unless I am missing that logic?
image

Happy to get on a call to discuss possible approaches for this one if you think that would be helpful :)

**Review by OotTheMonk — CHANGES_REQUESTED** [review]
See comments on conversation tab

**Comment by lukeputz92** [comment]
Hey I'm going to close this for now. I haven't had the time to review and  when I was testing it seemed that the functionality is mostly correct. I was not able to reproduce the specific scenario that is mentioned in the issue, but it seems like a bit of an edge case. Thanks for taking the time to review.

**Pull request closed without merging**
